### ISSUE TITLE
Horse Racing Assignment ready for marking 

### ISSUE THREAD

**Issue by charlotteKoch** [charlotteKoch/ICS3U#4]
https://github.com/charlotteKoch/ICS3U/blob/master/Unit%20Six/src/com/bayviewglen/horseracing/HorseRacingAssignment.java

input files are in the same package as this file

**Comment by kevindeslauriers** [comment]
Excellent work - I like the ability to add a player.  There seems to be an issue when choosing a horse after the second race. It thinks that I have already picked that horse?

Your code was very well written and organised.

I don't think you need to tell people they did not bet on a horse. I thinking showing the horses when you state that you want to bet would make it easier to play since you would not need to scroll up all the time to see the horses in the race.

96%
